### ISSUE TITLE
Run neo4j init script with the new docker-compose

### ISSUE THREAD

**Issue by swsachith** [Data-to-Insight-Center/cyberinfrastructure-knowledge-network#10]
Currently the docker-compose starts neo4j without the constraints for the node ids and embeddings. Need to add it at neo4j startup.

**Comment by nee1k** [comment]
Created a `constraints.cypher` script which runs after the `neo4j-server` has started.

[View code changes here.](https://github.com/Data-to-Insight-Center/cyberinfrastructure-knowledge-network/pull/9/commits/c4c14b191fec16d1ec03b8c91185818d081d1447)

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/ff0df312-e0d9-4a34-a214-1bdb2d70d783">
